### PR TITLE
Convert fluent-style configs to an array

### LINKED ISSUE #70: Add support for fluent-based configs
If your general.php file uses [the fluent-style for your config](https://craftcms.com/docs/4.x/config/#style-map-vs-fluent) you'll get  an error when running your tests:

```
  • Tests\ExampleTest > get '/' → assertOk 
   PHPUnit\Framework\ExceptionWrapper 

  array_merge(): Argument #1 must be of type array, craft\config\GeneralConfig given

  at vendor/markhuot/craft-pest/src/services/Config.php:19
     15▕         if ($filename === 'app.web') {
     16▕             $overrides = require __DIR__ . '/../config/app.web.php';
     17▕         }
     18▕ 
  ➜  19▕         return array_merge($original, $overrides);
     20▕     }
     21▕ }
     22▕ 
```

### Example config (using fluent syntax):

```php
<?php

use craft\config\GeneralConfig;
use craft\helpers\App;

return GeneralConfig::create()
    ->cpTrigger(App::env('CP_TRIGGER'))
    ->securityKey(App::env('SECURITY_KEY'))
    ->devMode(App::parseBooleanEnv('$DEV_MODE'));
```

---

Changing this to the standard array-based config will allow it to work:

```
PASS  Tests\ExampleTest
  ✓ get '/' → assertOk 

  Tests:  1 passed
  Time:   0.49s
```

### Example config (using arrays):

```php
<?php

use craft\config\GeneralConfig;
use craft\helpers\App;

return [
    'cpTrigger' => App::env('CP_TRIGGER'),
    'securityKey' => App::env('SECURITY_KEY'),
    'devMode' => App::parseBooleanEnv('$DEV_MODE')
];
```

### PR DESCRIPTION
**Pull request by aaronbushnell**
Resolves #70

### CODE REVIEW

File: src/services/Config.php [hunk 1]
```diff
@@ -11,6 +12,11 @@ public function getConfigFromFile(string $filename): array
     {
         $overrides = [];
         $original = parent::getConfigFromFile($filename);
+        
+        // Convert fluent-style configs to an array
+        if ($original instanceof GeneralConfig) {
+            $original = collect($original)->toArray();
+        }
```
Comment (markhuot) [inline src/services/Config.php:19]: This is nifty and definitely solves the problem. Thanks for figuring this out.

However, I think it'd be cleaner to add an early bail instead of forcing every config through this custom code. E.g., we'd need to move the original to the top, and add the early exit,

```php
$original = parent::getConfigFromFile($filename);
if (!is_array($original) || $filename !== 'app.web') {
  return $original;
}
```

then, below the bail we could assume we're operating on `app.web` (which doesn't have a fluent style config setup yet,

```
return array_merge($original, require __DIR__ . '/../config/app.web.php');
```

Make sense? I like this because it it's more clear that we're just not going to touch anything _other_ than `app.web`.

**Review by markhuot — CHANGES_REQUESTED** [review]

File: src/services/Config.php (hunk 1 above)
Comment (aaronbushnell) [reply src/services/Config.php:19]: I think I'm tracking with ya, @markhuot! Would the early exit look like this because `$original` isn't an array in a fluent-style config and needs to be coerced to one?

```php
public function getConfigFromFile(string $filename): array
{
    $original = parent::getConfigFromFile($filename);

    if (!is_array($original) || $filename !== 'app.web') {
        return collect($original)->toArray();
    }

    return array_merge($original, require __DIR__ . '/../config/app.web.php');
}
```

**Comment by aaronbushnell** [comment]
Made that suggested tweak, @markhuot  (if I'm following you correctly, that is!)

File: src/services/Config.php (hunk 1 above)
Comment (markhuot) [reply src/services/Config.php]: In other words that `return collect($original)…` could probably just be `return $original;`.

Comment (aaronbushnell) [reply src/services/Config.php]: Ooooh—I'm following you, @markhuot. Okay, just modified this early return. Had to revise the function's return types to `array|BaseConfig` since it can be either/or now.

Comment (markhuot) [reply src/services/Config.php]: Ah! This is great.

Just one issue on Craft 3.7, there’s no `BaseConfig` so we get a syntax error. Can you move the typehint to a docblock so it doesn’t break on 3.7 and I think that’ll do it!

File: src/services/Config.php [hunk 2]
```diff
@@ -3,19 +3,17 @@
 namespace craft\services;
 
 use craft\config\BaseConfig;
-use markhuot\craftpest\web\Application;
 
 class Config extends \markhuot\craftpest\overrides\Config
 {
-    public function getConfigFromFile(string $filename): array
+    public function getConfigFromFile(string $filename): array|BaseConfig
```
Comment (markhuot) [inline src/services/Config.php:9]:
```suggestion
    /**
     * @return array|BaseConfig
     */
    public function getConfigFromFile(string $filename)
```

Comment (aaronbushnell) [reply src/services/Config.php:9]: Great idea, @markhuot!

**Comment by markhuot** [comment]
I had to bring back the `:array` return type because PHP is a stickler for inheritance. But the rest is great. Merging!
